server:
  port: 8084
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-trade
    host: localhost
  swagger:
    title: "交易服务"
    desc: "交易服务接口文档"
    package: "com.hmall.trade.controller"