server:
  port: 8085
hm:
  db:
    database: hm-trade
    host: localhost
  swagger:
    title: "支付服务"
    desc: "支付服务接口文档"
    package: "com.hmall.pay.controller"
  mq:
    host: localhost
    port: 5672
    username: fzy
    password: fengziyang
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123