server:
  port: 8082
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-cart
    host: localhost
  swagger:
    title: "购物车服务"
    desc: "购物车服务接口文档"
    package: "com.huiminpay.cart.controller"
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123