server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true #开启线程隔离
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8180
      http-method-specify: true
hm:
  db:
    database: hm-cart
    host: localhost
  swagger:
    title: "购物车服务"
    desc: "购物车服务接口文档"
    package: "com.hmall.cart.controller"
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123