server:
  port: 8081
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-item
    host: localhost
  swagger:
    title: "商品服务"
    desc: "商品服务接口文档"
    package: "com.hmall.item.controller"
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123